name: Test
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        node: ['14', '16', '17', '18', '19', '20', '21']
    name: Node ${{ matrix.node }}
    # https://docs.github.com/en/actions/learn-github-actions/expressions#example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up node ${{ matrix.node }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ matrix.node}}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run tests with coverage
        run: yarn test:coverage
